Add release action
akashic-games/akashic-engine-standalone-release-action pull request #2
Opened 2021-04-16 12:14 UTC by kamakiri01

## このpull requestが解決する内容

GitHub Actions を使用したリリース手段を追加します。
一旦以下の順序を想定していますが、他の方法など含めコメントをいただければと思います。

### 更新順序

- akashic-engine が更新される
- `Upload Distribution` actions が1日1回 akashic-engine のバージョンを確認する
- 更新があれば、これを取り込んだ PR を作成する
  - ex: https://github.com/yu-ogi/akashic-engine-standalone-release-action/pull/9
- PR が main ブランチにマージされると、`Hook Main and Tag` actions が新しいタグを最新コミットに付ける
- 新しいタグが付くと、 `Release and Upload Assets` actions がリリースを作成する

2021-04-19 03:43 UTC, yu-ogi reviewed
更新順序は正しいように思います。 👍 👍 
動作も良さそうですが、全体的に名前が食い違っていそうなのが気になりました。

2021-04-19 03:43 UTC, yu-ogi commented on .github/workflows/hook_main_and_tag.yml
> +          npm run build
ビルドって必要でしょうか。tag をうつだけなら不要そうに思いました。

2021-04-19 03:43 UTC, yu-ogi commented on .github/workflows/upload_artifact.yml
> +name: Upload Distribution
こちら名前と動作が一致していないように見えます。「Update internal modules」とかでしょうか。

2021-04-19 03:43 UTC, yu-ogi commented on .github/workflows/upload_artifact.yml
> +    - cron:  '0 0 * * *'
コロン後の空白文字列が気になりました。

2021-04-19 11:41 UTC, kamakiri01 commented on .github/workflows/upload_artifact.yml
> +    - cron:  '0 0 * * *'
直します。

2021-04-19 11:41 UTC, kamakiri01 commented on .github/workflows/upload_artifact.yml
> +name: Upload Distribution
リネームします。

2021-04-19 11:41 UTC, kamakiri01 commented on .github/workflows/hook_main_and_tag.yml
> +          npm run build
`deploy` の中身的に `ci` だけで良さそうです。ビルドは消します。

2021-04-19 11:41 UTC, kamakiri01 commented on .github/workflows/hook_main_and_tag.yml
> +      - name:  set new tag
直します。

2021-04-19 11:41 UTC, kamakiri01 commented on scripts/check_and_release_tag.js
> +const aksVer = semverClean(pkg.devDependencies["@akashic/akashic-engine"]); // "~3.0.0" -> "3.0.0"
`semver.clean` に `3.0.0-beta.0` のような beta が付与されたバージョン名を渡すと null が返るので、チルダとキャレットを削除するだけの関数に置き換えています。
beta 系バージョンで動かさない場合は `semver.clean` で良いと思います。

2021-04-19 11:41 UTC, kamakiri01 commented on .github/workflows/upload_artifact.yml
> +      - name:  Check version
LATEST_VERSION の PR を作成済みの場合は `create-pull-request` step を再実行しない、という挙動を作る意図のものですが、利用側が自分のコミットミスで載っていないですね…

元々は、この step の後段で、
`if: ${{ steps.version.outputs.NEW_VERSION!= steps.curent_version.outputs.CURRENT_VERSION && steps.check_version.outputs.ALREADY_PR == '' }}`  のような条件を `create-pull-request` step に持たせて、PR の多重生成やactionsの失敗（おそらくブランチを切るタイミングで失敗するはず？）を抑止するつもりでした。

この条件付けが必要かは確認をしたいです。

2021-04-19 11:41 UTC, kamakiri01 commented on .github/workflows/upload_artifact.yml
> +          echo "::set-output name=NEW_VERSION::$VERSION"
`LATEST_VERSION` で揃えます。

2021-04-19 11:41 UTC, kamakiri01 commented on .github/workflows/upload_artifact.yml
> +      - name: Get current version of akashic-engine
別コメントの `name: Check version` と併せて使う予定でしたがコミットミスで機能しなくなっていました。
そちらの条件付けが不要であればこちらも不要な step です。

2021-04-19 11:41 UTC, kamakiri01 commented on .github/workflows/hook_main_and_tag.yml
> +  cache-version: v1
追加します。

2021-04-19 11:41 UTC, kamakiri01 commented on .github/workflows/hook_main_and_tag.yml
> +          npm ci
追加します。

2021-04-19 11:41 UTC, kamakiri01 commented on .github/workflows/hook_main_and_tag.yml
> +name: Hook Main and Tag
確かに、直します（ファイル名も揃えます）

2021-04-20 01:47 UTC, yu-ogi requested changes
* 対応されていない項目が resolve されていて混乱するので、 resolve はこちらで確認させて頂く形にしてください。
* PullRequest の説明欄にある更新の順序を README に記載しておきたいです。

2021-04-20 01:47 UTC, yu-ogi commented on .github/workflows/hook_main_and_tag.yml
> +name: Hook Main and Tag
resolve されていますがこちら対応されていますか？

2021-04-20 01:47 UTC, yu-ogi commented on .github/workflows/hook_main_and_tag.yml
> +  cache-version: v1
resolve されていますがこちら対応されていますか？

2021-04-20 01:47 UTC, yu-ogi commented on .github/workflows/release_and_upload_assets.yml
> +name: Update internal modules
意図のよくわからない変更です。

2021-04-20 01:47 UTC, yu-ogi commented on .github/workflows/upload_artifact.yml
> +name: Upload Distribution
resolve されていますがこちら対応されていますか？

2021-04-20 01:47 UTC, yu-ogi commented on .github/workflows/upload_artifact.yml
> +      - name:  Check version
現段階では不要かと思います。理由は以下です。
* この step に来た段階で中断を判断しても対してメリットにならないため
   * 少なくとも `npm run build` する前に判断できるようにすべきかと思います。
* どちらかというと、既存の PullRequest の内容を判断して必要があれば (差分があれば) 上書きする形で更新してほしいため

2021-04-20 01:47 UTC, yu-ogi commented on scripts/check_and_release_tag.js
> +const aksVer = semverClean(pkg.devDependencies["@akashic/akashic-engine"]); // "~3.0.0" -> "3.0.0"
なるほど、ありがとうございます。できれば予め PullRequest 上にコメントを書いていただけるとありがたいです。

2021-04-20 01:47 UTC, yu-ogi commented on .github/workflows/upload_artifact.yml
> +          branch: upload_artifact_file/${{ steps.version.outputs.LATEST_VERSION }}
基となったたたき台からで恐縮ですが `update_akashic_engine/...` というブランチ名にしておきたいです。

2021-04-20 07:12 UTC, kamakiri01 commented on .github/workflows/release_and_upload_assets.yml
> +name: Update internal modules
うっ、ひどいミスです。戻します。

2021-04-20 07:12 UTC, kamakiri01 commented on .github/workflows/upload_artifact.yml
> +name: Upload Distribution
対応漏れでした。次のコミットで対応します。

2021-04-20 07:12 UTC, kamakiri01 commented on scripts/check_and_release_tag.js
> +const aksVer = semverClean(pkg.devDependencies["@akashic/akashic-engine"]); // "~3.0.0" -> "3.0.0"
そうします 🙇

2021-04-20 07:13 UTC, kamakiri01 commented on .github/workflows/upload_artifact.yml
> +          branch: upload_artifact_file/${{ steps.version.outputs.LATEST_VERSION }}
ブランチ名置き換えます。

2021-04-20 07:13 UTC, kamakiri01 commented on .github/workflows/upload_artifact.yml
> +      - name: Get current version of akashic-engine
https://github.com/akashic-games/akashic-engine-standalone-release-action/pull/2#discussion_r616281099 に対応して、この step は削除します。

2021-04-20 07:19 UTC, kamakiri01 commented on .github/workflows/upload_artifact.yml
> +      - name:  Check version
> 上書きする形で更新してほしい
なるほどです。一旦この挙動周りは削除します。

2021-04-21 03:26 UTC, yu-ogi commented on .github/workflows/upload_artifact.yml
> +name: Update internal modules
こちらファイル名も `update_internal_modules.yml` とかにしておきたいです。

2021-04-21 03:26 UTC, yu-ogi commented on .github/workflows/upload_artifact.yml
> +    name: Upload Distribution
こちらも削除しても良さそうですね。

2021-04-21 03:26 UTC, yu-ogi commented on README.md
> +- PR が main ブランチにマージされると、`Hook Main and Tag` actions が新しいタグを最新コミットに付ける
* https://github.com/akashic-games/akashic-engine-standalone-release-action/pull/2#discussion_r615505813 の追従をお願いします。
* action ではなく workflow の方が適切かなと思います。

2021-04-21 11:52 UTC, kamakiri01 commented on README.md
> +- PR が main ブランチにマージされると、`Hook Main and Tag` actions が新しいタグを最新コミットに付ける
追従します。

2021-04-21 11:52 UTC, kamakiri01 commented on .github/workflows/upload_artifact.yml
> +    name: Upload Distribution
こちらも削除します。

2021-04-21 11:52 UTC, kamakiri01 commented on .github/workflows/upload_artifact.yml
> +name: Update internal modules
リネームします。

2021-04-21 11:52 UTC, kamakiri01 commented on .github/workflows/push_release_tag.yml
> +    name: Upload Distribution
jobのname系まとめて削除します。

2021-04-21 11:52 UTC, kamakiri01 commented on .github/workflows/push_release_tag.yml
> +  upload:
リネームします。

2021-04-21 11:52 UTC, kamakiri01 commented on .github/workflows/push_release_tag.yml
> +name: Hook Main and Tag
対応しました 🙇

2021-04-21 11:52 UTC, kamakiri01 commented on .github/workflows/push_release_tag.yml
> +          npm run deploy
そうですね、まとめます。

2021-04-21 12:57 UTC, dera- commented on .github/workflows/update_internal_modules.yml
> +          git commit -m "Update to ${{ steps.version.outputs.LATEST_VERSION }}"
ライブラリの更新が無い時にコミットせず終了するみたいな処理は必要かと思いますが、どこかでやられてますでしょうか？やられてない場合このコミットでエラーになると思います。

あと、masterブランチでコミットしているように見えますがこちら問題ないでしょうか？下のstepで実行されるcreate-pull-requestアクションがよしなに新しいブランチをチェックアウトしてくれる感じなんですかね？であれば大丈夫そうな気はしますが。

2021-04-22 02:22 UTC, yu-ogi commented on .github/workflows/update_internal_modules.yml
> +          git commit -m "Update to ${{ steps.version.outputs.LATEST_VERSION }}"
確かにコミットの差分が無ければ skip する処理は必要そうですね。参考までにたたき台の方で [technote-space/get-diff-action](https://github.com/marketplace/actions/get-diff-action) を利用した例を作ってみました。
https://github.com/yu-ogi/akashic-engine-standalone-release-action/pull/10/files

2021-04-22 09:20 UTC, kamakiri01 commented on .github/workflows/update_internal_modules.yml
> +          git commit -m "Update to ${{ steps.version.outputs.LATEST_VERSION }}"
ありがとうございます。

ほぼそのまま使わせてもらいました。
（ifの位置は先頭が読みやすいと思えたのと https://docs.github.com/ja/actions/reference/workflow-syntax-for-github-actions を参考にして頭に移しました）

2021-04-22 10:15 UTC, yu-ogi approved these changes
LGTMです。

2021-04-22 10:15 UTC, yu-ogi commented on .github/workflows/push_release_tag.yml
> +          fetch-depth: 0
すいません、今更ながらこれ削除しても良さそうですね。(履歴は不要なはずなので)
https://github.com/actions/checkout#usage

2021-04-22 10:15 UTC, yu-ogi commented on .github/workflows/update_internal_modules.yml
> +          fetch-depth: 0
ここも。

2021-04-22 11:11 UTC, dera- approved these changes
コメントしましたが、approveします

2021-04-22 11:11 UTC, dera- commented on .github/workflows/update_internal_modules.yml
> +      - uses: technote-space/get-diff-action@v4
細かいですが、この`-`は要らないように思えます

2021-04-22 11:11 UTC, dera- commented on .github/workflows/update_internal_modules.yml
> +        if: env.GIT_DIFF
環境変数`GIT_DIFF`はこのワークフローでは定義されてないように見えますが、get-diff-actionで定義される感じなんですかね？であればその旨のコメントも欲しい気がしました。

2021-04-22 12:12 UTC, kamakiri01 commented on .github/workflows/update_internal_modules.yml
> +        if: env.GIT_DIFF
`technote-space/get-diff-action@v4 のデフォルト名として内部で定義されている認識です。
https://github.com/technote-space/get-diff-action/blob/master/README.ja.md#%E5%87%BA%E5%8A%9B

2021-04-22 12:12 UTC, kamakiri01 commented on .github/workflows/update_internal_modules.yml
> +      - uses: technote-space/get-diff-action@v4
確かに、上行でnameがあるので `-` は不要でした。削除します。

2021-04-22 12:12 UTC, kamakiri01 commented on .github/workflows/update_internal_modules.yml
> +          fetch-depth: 0
こちらも削除します。

2021-04-22 12:12 UTC, kamakiri01 commented on .github/workflows/push_release_tag.yml
> +          fetch-depth: 0
削除します。

2021-04-22 12:23 UTC, merged